#pragma config(Sensor, in8,    LiftP,          sensorPotentiometer)
#pragma config(Sensor, dgtl5,  TR,             sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  TL,             sensorQuadEncoder)
#pragma config(Motor,  port1,           topLeft,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           topRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftLiftMD,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightLiftMD,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           leftLiftU,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           rightLiftU,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftclaw,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rightclaw,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           bottomLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          bottomRight,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

static const int LIFT_UP_VELOCITY = 127;
static const int LIFT_DOWN_VELOCITY = -127;
static const int NONE_CONST = 0;
static const int SINGLE_STAR_CONST = -15;
static const int FULL_POWER = 127;
bool deltaApply;
bool claw;

//Converts distance needed to travel from centimeters to the counts from the encoders
long calculate (long distancetraveled){
	long radius = (2.75/2)*2.54;
	long circumference = radius*2*PI;
	long encoderCounts = (360/circumference)*distancetraveled;
	return encoderCounts;
}

//Moving Forward

void forwardstraight(long encoderCounts, bool lift){

	if(lift == false)
		SensorValue[TR] = 0;
	SensorValue[TL] = 0;

	if(SensorValue[TR]*cos(45)*2.54 <= encoderCounts && abs(SensorValue[TL])*cos(45)*2.54 <= encoderCounts
		){
		motor[topRight] = FULL_POWER;
		motor[topLeft] =  FULL_POWER;
		motor[bottomRight]= FULL_POWER;
		motor[bottomLeft] = FULL_POWER;

	}
	else{
		motor[topRight] = 0;
		motor[topLeft] =  0;
		motor[bottomRight]= 0;
		motor[bottomLeft] = 0;
	}


}

//Moving Backwards

void backwardstraight(long encoderCounts, bool lift2){

	if(lift2 == false){
		SensorValue[TR] = 0;
		SensorValue[TL] = 0;
	}

	if(SensorValue[TR]*cos(45)*2.54 <= encoderCounts && abs(SensorValue[TL])*cos(45)*2.54 <= encoderCounts
		){
		motor[topRight] = -FULL_POWER;
		motor[topLeft] =  -FULL_POWER;
		motor[bottomRight]= -FULL_POWER;
		motor[bottomLeft] = -FULL_POWER;

	}
	else{

		motor[topRight] = 0;
		motor[topLeft] =  0;
		motor[bottomRight]= 0;
		motor[bottomLeft] = 0;
	}

}

//Turning Left

void turnL(long encoderCounts){


	SensorValue[TR] = 0;
	SensorValue[TL] = 0;

	while (SensorValue[TR]*cos(45)*2.54 <= encoderCounts && abs(SensorValue[TL])*cos(45)*2.54 <= encoderCounts
		){
		motor[topRight] = FULL_POWER;
		motor[topLeft] =  -FULL_POWER;
		motor[bottomRight]= FULL_POWER;
		motor[bottomLeft] = -FULL_POWER;


	}
	motor[topRight] = 0;
	motor[topLeft] =  0;
	motor[bottomRight]= 0;
	motor[bottomLeft] = 0;


}

//Turning Right

void turnR(long encoderCounts){

	SensorValue[TR] = 0;
	SensorValue[TL] = 0;

	while (SensorValue[TR]*cos(45)*2.54 <= encoderCounts && abs(SensorValue[TL])*cos(45)*2.54 <= encoderCounts
		){
		motor[topRight] = -FULL_POWER;
		motor[topLeft] =  FULL_POWER;
		motor[bottomRight]= -FULL_POWER;
		motor[bottomLeft] = FULL_POWER;

	}

	motor[topRight] = 0;
	motor[topLeft] =  0;
	motor[bottomRight]= 0;
	motor[bottomLeft] = 0;
}

void clawGrab(long sec){

	motor[leftclaw] = FULL_POWER;
	motor[rightclaw] = FULL_POWER;
	wait1Msec(sec*1000);

}

void clawOpen(long sec){

	motor[leftclaw] = -FULL_POWER;
	motor[rightclaw] = -FULL_POWER;
	wait1Msec(sec*1000);

}

void SLift(){

	while(SensorValue[LiftP] < 250){
		motor[leftLiftMD] = LIFT_UP_VELOCITY;
		motor[leftLiftU] = LIFT_UP_VELOCITY;
		motor[rightLiftMD] = LIFT_UP_VELOCITY;
		motor[rightLiftU] = LIFT_UP_VELOCITY;
	}
	motor[leftLiftMD] = 0;
	motor[leftLiftU] = 0;
	motor[rightLiftMD] = 0;
	motor[rightLiftU] = 0;
}

void throw(bool move, long distance){
	if(move){

		long x = distance;

		SensorValue[TR] = 0;
		SensorValue[TL] = 0;

		while(SensorValue[TR]*cos(45)*2.54 <= calculate(x) && abs(SensorValue[TL])*cos(45)*2.54 <= calculate(x)&& SensorValue[LiftP] < 2500) {
			if(SensorValue[LiftP] < 2500){  //2520
				motor[leftLiftMD] = LIFT_UP_VELOCITY;
				motor[leftLiftU] = LIFT_UP_VELOCITY;
				motor[rightLiftMD] = LIFT_UP_VELOCITY;
				motor[rightLiftU] = LIFT_UP_VELOCITY;
				if(SensorValue[LiftP] > 2300 && SensorValue[LiftP] < 2400){
					clawOpen(0.2);
				}
			}
			else{
				motor[leftLiftMD] = 0;
				motor[leftLiftU] = 0;
				motor[rightLiftMD] = 0;
				motor[rightLiftU] = 0;
			}
			if(SensorValue[TR]*cos(45)*2.54 <= calculate(x) && abs(SensorValue[TL])*cos(45)*2.54 <= calculate(x)
				) {
				backwardstraight(calculate(x), true);
			}
		}
		motor[leftLiftMD] = 0;
		motor[leftLiftU] = 0;
		motor[rightLiftMD] = 0;
		motor[rightLiftU] = 0;
		motor[rightclaw] = 0;
		motor[leftclaw] = 0;

	}
	else if(move == false){

		SensorValue[TR] = 0;
		SensorValue[TL] = 0;

		while(SensorValue[LiftP] < 2500) {
			if(SensorValue[LiftP] < 2500){  //2520
				motor[leftLiftMD] = LIFT_UP_VELOCITY;
				motor[leftLiftU] = LIFT_UP_VELOCITY;
				motor[rightLiftMD] = LIFT_UP_VELOCITY;
				motor[rightLiftU] = LIFT_UP_VELOCITY;
				//if(SensorValue[LiftP] > 2100){
				//	clawOpen(0.2);
				//}
			}
			else{
				motor[leftLiftMD] = 0;
				motor[leftLiftU] = 0;
				motor[rightLiftMD] = 0;
				motor[rightLiftU] = 0;
			}
		}
		motor[leftLiftMD] = 0;
		motor[leftLiftU] = 0;
		motor[rightLiftMD] = 0;
		motor[rightLiftU] = 0;
		motor[rightclaw] = 0;
		motor[leftclaw] = 0;
	}

	/////////////////////////////////////////////////////////

}

void LiftDown(bool move2, long distance2){
	if(move2){

		long x = distance2;

		SensorValue[TR] = 0;
		SensorValue[TL] = 0;

		while(SensorValue[TR]*cos(45)*2.54 <= calculate(x) && abs(SensorValue[TL])*cos(45)*2.54 <= calculate(x)&& SensorValue[LiftP] > 120) {
			if(SensorValue[LiftP] > 120){
				motor[leftLiftMD] = LIFT_DOWN_VELOCITY;
				motor[leftLiftU] = LIFT_DOWN_VELOCITY;
				motor[rightLiftMD] = LIFT_DOWN_VELOCITY;
				motor[rightLiftU] = LIFT_DOWN_VELOCITY;
			}
			else{
				motor[leftLiftMD] = 0;
				motor[leftLiftU] = 0;
				motor[rightLiftMD] = 0;
				motor[rightLiftU] = 0;
			}
			if(SensorValue[TR]*cos(45)*2.54 <= calculate(x) && abs(SensorValue[TL])*cos(45)*2.54 <= calculate(x)
				) {
				forwardstraight(calculate(x), true);
			}
		}
		motor[leftLiftMD] = 0;
		motor[leftLiftU] = 0;
		motor[rightLiftMD] = 0;
		motor[rightLiftU] = 0;

	}

	else if(move2 == false){

		SensorValue[TR] = 0;
		SensorValue[TL] = 0;

		while(SensorValue[LiftP] > 120) {
			if(SensorValue[LiftP] > 120){
				motor[leftLiftMD] = LIFT_DOWN_VELOCITY;
				motor[leftLiftU] = LIFT_DOWN_VELOCITY;
				motor[rightLiftMD] = LIFT_DOWN_VELOCITY;
				motor[rightLiftU] = LIFT_DOWN_VELOCITY;
			}
			else{
				motor[leftLiftMD] = 0;
				motor[leftLiftU] = 0;
				motor[rightLiftMD] = 0;
				motor[rightLiftU] = 0;
			}
		}
		motor[leftLiftMD] = 0;
		motor[leftLiftU] = 0;
		motor[rightLiftMD] = 0;
		motor[rightLiftU] = 0;
	}

	/////////////////////////////////////////////////////////////

}
void pre_auton() {
	bStopTasksBetweenModes = true;
}
/*=============================================*/
/*                 AUTONOMOUS                  */
/*=============================================*/

task autonomous() {
	//Starting on the right side of the field
	throw(true,10);
	clawGrab(0.6);
	forwardstraight(calculate(70), false); //Subtract 10cm to take account for momentum
	turnL(calculate(80));
	//throw and back
	forwardstraight(calculate(5),false);
	turnR(calculate(35));
	//open claw 25%
	forwardstraight(calculate(110), false);
	//close claw
	turnL(35);
	//throw
	backwardstraight(calculate(10),false);
	//back
	forwardstraight(calculate(60),false);
	turnL(35);
	forwardstraight(calculate(50),false);
	//close claw
	turnR(35);
	//throw
	backwardstraight(calculate(60),false);
	//back
	forwardstraight(calculate(5),false);
	turnL(17); //45 deg
	forwardstraight(calculate(75),false); //60 and 60
	turnR(17);
	forwardstraight(calculate(50),false);
	//open claw
	turnR(35);
	forwardstraight(calculate(110),false);
	//close and lift claw
	turnR(35);
	backwardstraight(calculate(120),false);
	//throw and back
	forwardstraight(calculate(5),false);
	turnR(17);
	forwardstraight(calculate(75),false);
	turnL(17);
	//open claw
	forwardstraight(calculate(50),false);
	//close and lift claw
	backwardstraight(calculate(120),false);
	//throw
	//down and open
	forwardstraight(calculate(10),false);
	turnR(35);
	//close and lift
	turnL(35);
	forwardstraight(calculate(60),false);
	//open
	forwardstraight(calculate(50),false);
	//close and lift
	backwardstraight(calculate(120),false);
	//throw
	forwardstraight(calculate(10),false);
	turnL(35);
	forwardstraight(calculate(240),false);
	//open
	forwardstraight(calculate(50),false);
	turnR(35);
	forwardstraight(calculate(60),false);
	//open
	forwardstraight(calculate(50),false);
	//close
	backwardstraight(calculate(120),false);
	//throw


	clawGrab(0.5);
	SLift();
	backwardstraight(calculate(50), false);
	turnL(calculate(35));
	throw(true,40);
	LiftDown(true, 40);
	forwardstraight(calculate(50), false);
	turnR(calculate(35));
	forwardstraight(calculate(30), false);
	turnL(calculate(35));
	forwardstraight(calculate(30), false);
	clawGrab(0.5);
	SLift();
	throw(true, 100);
	LiftDown(true,100);
}
// |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
// |     _                                   _   |
// |    | |                                 | |  |
// | ___| | __ ___   _____  __ _ _   _  __ _| |_ |
// |/ __| |/ _` \ \ / / __|/ _` | | | |/ _` | __||
// |\__ \ | (_| |\ V /\__ \ (_| | |_| | (_| | |_ |
// ||___/_|\__,_| \_/ |___/\__, |\__,_|\__,_|\__||
// |                          | |                |
// |                          |_|                |
// |~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~|
void driveCode();
task usercontrol() {
	while (true) {

		/*if(vexRT[Btn5U] == 0 && vexRT[Btn5D] == 0){
		//	motor[leftLiftMD] = -SINGLE_STAR_CONST;
		//motor[leftLiftU] =  -SINGLE_STAR_CONST;
		//motor[rightLiftMD]= -SINGLE_STAR_CONST;
		//motor[rightLiftMD] = -SINGLE_STAR_CONST;

		if (vexRT[Btn6U] == 1) {
		motor[leftclaw] = FULL_POWER;
		motor[rightclaw] = FULL_POWER;
		} else if (vexRT[Btn6D] == 1) {
		motor[leftclaw] = -FULL_POWER;
		motor[rightclaw] = -FULL_POWER;
		} else {
		motor[leftclaw] = 0;
		motor[rightclaw] = 0;
		}
		driveCode();
		}
		else {*/

		if (vexRT[Btn5U] == 1) {
			motor[leftLiftMD] = LIFT_UP_VELOCITY;
			motor[leftLiftU] = LIFT_UP_VELOCITY;
			motor[rightLiftMD] = LIFT_UP_VELOCITY;
			motor[rightLiftU] = LIFT_UP_VELOCITY;
		}
		else if (vexRT[Btn5D] == 1 && SensorValue[LiftP] > 120) {
			motor[leftLiftMD] = LIFT_DOWN_VELOCITY;
			motor[leftLiftU] = LIFT_DOWN_VELOCITY;
			motor[rightLiftMD] = LIFT_DOWN_VELOCITY;
			motor[rightLiftU] = LIFT_DOWN_VELOCITY;
		}
		else {
			motor[leftLiftMD] = 0;
			motor[leftLiftU] = 0;
			motor[rightLiftMD] = 0;
			motor[rightLiftU] = 0;
		}

		if (vexRT[Btn8L] == 1) {

			throw(false, 1);

		}
		if (vexRT[Btn6U] == 1) {
			motor[leftclaw] = FULL_POWER;
			motor[rightclaw] = FULL_POWER;
			//claw = true;
			} else if (vexRT[Btn6D] == 1) {
			motor[leftclaw] = -FULL_POWER;
			motor[rightclaw] = -FULL_POWER;
			//claw = false;
			} else {
			motor[leftclaw] = 0;
			motor[rightclaw] = 0;
			/*	if(claw == true){
			motor[leftclaw] = FULL_POWER;
			motor[rightclaw] = FULL_POWER;

			}*/


		}
		driveCode();
	}
}

void driveCode () {

	motor[topRight] = vexRT[Ch3] -vexRT[Ch1] -vexRT[Ch4];//RFM = Right Front Motor
	motor[topLeft] = vexRT[Ch3] +vexRT[Ch1] +vexRT[Ch4];//LFM = Left Front Motor
	motor[bottomRight] = vexRT[Ch3] -vexRT[Ch1] +vexRT[Ch4];//RBM = Right Back Motor
	motor[bottomLeft] = vexRT[Ch3] + vexRT[Ch1] -vexRT[Ch4];//LBM = Left Back Motor

}
